### Request verification code for phone 13800000000
POST http://localhost:8080/api/user/code?phone=13800000000

### Register user (if needed)
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "phone": "13800000000",
  "code": "753908",
  "password": "pass1234",
  "nickName": "测试用户1"
}

### Login (you need the code from server logs or set in Redis)
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "phone": "13800000000",
  "code": "591348"
}


### Get profile
GET http://localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzcyI6ImplbXkiLCJleHAiOjE3NjMwMTM0ODYsIm5iZiI6MTc2MjkyNzA4NiwiaWF0IjoxNzYyOTI3MDg2fQ.-1jeTUCT5FjXXQgFcA4bY0n8YCHw6gjAOhBo62wDQto


### Update profile
PUT http://localhost:8080/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzcyI6ImplbXkiLCJleHAiOjE3NjEwMTU2NzEsIm5iZiI6MTc2MDkyOTI3MSwiaWF0IjoxNzYwOTI5MjcxfQ.JlZMB_5Y5yQiAJCe4oY_U1gxmeJ23aR98Izon8jRCuA

{
  "NickName" : "Jemy1",
		"Icon" : "None"
}

### Seckill purchase 
POST http://localhost:8080/api/voucher-order/seckill/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzcyI6ImplbXkiLCJleHAiOjE3NjExMzYzNTUsIm5iZiI6MTc2MTA0OTk1NSwiaWF0IjoxNzYxMDQ5OTU1fQ.1x8L4PJ9tncZBX2p1WqwGa7-YmZkGb7B_STEeCsuuAo



### Logout current user (blacklist token)
POST http://localhost:8080/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzcyI6ImplbXkiLCJleHAiOjE3NjMwMTM0ODYsIm5iZiI6MTc2MjkyNzA4NiwiaWF0IjoxNzYyOTI3MDg2fQ.-1jeTUCT5FjXXQgFcA4bY0n8YCHw6gjAOhBo62wDQto

